-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    points INTEGER DEFAULT 0,
    level INTEGER DEFAULT 1,
    streak_days INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. PETS TABLE
CREATE TABLE IF NOT EXISTS public.pets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(20) DEFAULT 'dog',
    level INTEGER DEFAULT 1,
    experience INTEGER DEFAULT 0,
    hunger INTEGER DEFAULT 50,
    happiness INTEGER DEFAULT 50,
    energy INTEGER DEFAULT 50,
    last_interaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pets_energy_check CHECK (energy >= 0 AND energy <= 100),
    CONSTRAINT pets_happiness_check CHECK (happiness >= 0 AND happiness <= 100),
    CONSTRAINT pets_hunger_check CHECK (hunger >= 0 AND hunger <= 100)
);

-- 3. ACHIEVEMENTS TABLE
CREATE TABLE IF NOT EXISTS public.achievements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    criteria_type VARCHAR(50) NOT NULL,
    criteria_value INTEGER NOT NULL,
    reward_points INTEGER DEFAULT 50,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    badge_image_url VARCHAR(255)
);

-- 4. SHOP ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.shop_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    item_type VARCHAR(20) NOT NULL,
    effect_type VARCHAR(20) NOT NULL,
    effect_value INTEGER DEFAULT 10,
    cost_points INTEGER NOT NULL,
    rarity VARCHAR(20) DEFAULT 'common',
    image_url VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. TASKS TABLE
CREATE TABLE IF NOT EXISTS public.tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES public.users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    priority VARCHAR(10) DEFAULT 'medium',
    difficulty VARCHAR(10) DEFAULT 'medium',
    due_date TIMESTAMP,
    completed BOOLEAN DEFAULT false,
    completed_at TIMESTAMP,
    points_worth INTEGER DEFAULT 10,
    points_earned INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. USER INVENTORY & ACHIEVEMENTS (Join Tables)
CREATE TABLE IF NOT EXISTS public.user_achievements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES public.users(id) ON DELETE CASCADE,
    achievement_id INTEGER REFERENCES public.achievements(id) ON DELETE CASCADE,
    earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, achievement_id)
);


CREATE TABLE IF NOT EXISTS public.user_inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES public.users(id) ON DELETE CASCADE,
    item_id INTEGER REFERENCES public.shop_items(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 1,
    purchased_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, item_id)
);

-- 7. INDEXES
CREATE INDEX idx_inventory_user ON public.user_inventory(user_id);
CREATE INDEX idx_pets_user_id ON public.pets(user_id);
CREATE INDEX idx_tasks_due_date ON public.tasks(due_date) WHERE (completed = false);

-- 8. SEED DATA
INSERT INTO public.shop_items (id, name, description, item_type, effect_type, effect_value, cost_points, rarity)
VALUES 
(1, 'Premium Pet Food', 'Delicious meal', 'food', 'hunger', 30, 20, 'common'),
(2, 'Bouncy Ball', 'Fun toy', 'toy', 'happiness', 25, 35, 'uncommon'),
(13, 'Gourmet Feast', 'A luxurious meal that satisfies hunger completely', 'food', 'hunger', 50, 45, 'rare'),
(14, 'Energy Snack', 'Quick energy boost for your pet', 'food', 'energy', 25, 30, 'uncommon'),
(15, 'Healthy Treat', 'Nutritious snack that boosts happiness', 'food', 'happiness', 20, 25, 'common'),
(16, 'Squeaky Mouse', 'Irresistible toy for cats', 'toy', 'happiness', 30, 40, 'uncommon'),
(17, 'Flying Disc', 'Perfect for active dogs', 'toy', 'happiness', 35, 50, 'rare'),
(18, 'Puzzle Feeder', 'Mental stimulation toy', 'toy', 'happiness', 20, 55, 'rare'),
(19, 'Rainbow Scarf', 'Colorful accessory for any pet', 'accessory', 'cosmetic', 0, 60, 'uncommon'),
(20, 'Magic Cape', 'Makes your pet look heroic', 'accessory', 'cosmetic', 0, 120, 'epic'),
(21, 'Sparkly Collar', 'Shiny accessory that boosts mood', 'accessory', 'happiness', 10, 45, 'rare'),
(22, 'Super Elixir', 'Restores all stats by 20', 'consumable', 'all', 20, 80, 'epic'),
(23, 'Happiness Potion', 'Instantly boosts happiness', 'consumable', 'happiness', 40, 50, 'rare'),
(24, 'Energy Drink', 'Restores 50 energy', 'consumable', 'energy', 50, 45, 'uncommon'),
(25, 'Legendary Feast', 'A meal fit for a champion', 'food', 'all', 40, 100, 'legendary'),
(26, 'Laser Pointer', 'Hours of entertainment', 'toy', 'happiness', 45, 65, 'rare'),
(27, 'Golden Crown', 'Royal accessory', 'accessory', 'cosmetic', 0, 200, 'legendary'),
(28, 'Mystery Box', 'Surprise effect!', 'consumable', 'random', 0, 75, 'epic')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.achievements (id, name, description, criteria_type, criteria_value, reward_points)
VALUES 
(5, 'First Step', 'Complete your first task', 'tasks_completed', 1, 10),
(6, 'Task Master', 'Complete 10 tasks', 'tasks_completed', 10, 50),
(7, 'Productivity Guru', 'Complete 50 tasks', 'tasks_completed', 50, 200),
(8, 'Point Collector', 'Earn 100 points', 'points_earned', 100, 25),
(9, 'Point Millionaire', 'Earn 1000 points', 'points_earned', 1000, 100),
(10, 'Weekly Warrior', 'Maintain a 7-day streak', 'streak_days', 7, 75),
(11, 'Monthly Champion', 'Maintain a 30-day streak', 'streak_days', 30, 200),
(12, 'Pet Lover', 'Reach pet level 5', 'pet_level', 5, 50),
(13, 'Pet Master', 'Reach pet level 10', 'pet_level', 10, 100)
ON CONFLICT (id) DO NOTHING;