spring:
    application:
        name: motivatemate

    datasource:
        url: jdbc:postgresql://localhost:5432/motivatemate_dev
        driver-class-name: org.postgresql.Driver
        username: motivatemate_user
        #${DB_USERNAME:postgres}
        password: Pocwyg7swean
        #${DB_PASSWORD:postgres}

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect

    sql:
        init:
            mode: never

server:
    port: 8080

jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production}
    expiration: 86400000

logging:
  level:
    com.motivatemate: DEBUG
    org.hibernate.SQL: DEBUG
